### ISSUE TITLE
Walkthrough of how to install WSAHelper using MagiskOnWSA?

### ISSUE THREAD

**Issue by chip33** [LSPosed/WSAHelper#1]
Can you kindly provide a walkthrough of how to install WSAHelper using MagiskOnWSA?

**Comment by nin0-dev** [comment]
In WSA you go here https://github.com/LSPosed/WSAHelper/releases/tag/v1.0 and you download the APK and you install it.

**Comment by chip33** [comment]
Thanks, I just sideloaded it normally and it works.
