### ISSUE TITLE
How to uninstall 

### ISSUE THREAD

**Issue by chiragnahata** [LSPosed/WSAHelper#2]
How to uninstall WSAHelper

**Comment by thefallxo** [comment]
how did you install ?

**Comment by Mahasvan** [comment]
Connecting to WSA using adb and running
```
 adb uninstall org.lsposed.wsa.helper
```
worked for me

**Comment by matifali** [comment]
> Connecting to WSA using adb and running
> 
> ```
>  adb uninstall org.lsposed.wsa.helper
> ```
> 
> worked for me

Indeed this is the answer.
Or a more user-friendly option is to go to the control panel and find WSAHelper and uninstall. Windows Control Panel lets you uninstall individual apps installed within WSA.
